apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "redis-cluster-ha.fullname" . }}
spec:
  serviceName: {{ include "redis-cluster-ha.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "redis-cluster-ha.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "redis-cluster-ha.fullname" . }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - "redis-server"
            - "/etc/redis/redis.conf"
            - "--requirepass"
            - "{{ .Values.auth.password }}"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: redis-config
              mountPath: /etc/redis
          resources: {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: redis-config
          configMap:
            name: {{ include "redis-cluster-ha.fullname" . }}-config
            items:
              - key: redis.conf
                path: redis.conf
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
